
// Auto-generated by AutoPilot on 24-07-2023 at 01:22:38

const express = require('express');
const router = express.Router();

router.get('/toss', (req, res) => {
//let the toss begin
    const result = Math.random() < 0.5 ? "heads" : "tails"; // Generate random heads or tails
    res.status(200).json({result});
});

module.exports = router;