
// Auto-generated by AutoPilot on 24-07-2023 at 00:56:22

const express = require('express');
const router = express.Router();

// Route to generate cube of a number
router.get('/cube', (req, res) => {
    // Get the query parameter
    const { number } = req.query;

    // Check if the parameter is a number
    if(isNaN(number)) {
        // If not, send an error response
        return res.status(500).json({ error: 'Encountered an error' });
    } 

    // Calculate cube of the number
    const result = Math.pow(number, 3);

    // Return the result
    return res.status(200).json({ result });
});

module.exports = router;