
// Auto-generated by AutoPilot on 24-07-2023 at 01:19:22

const express = require('express');
const router = express.Router();

router.get('/barbie', (req, res) => {
    try {
        res.status(200).json({
            result: "I'm a barbie girl, in a barbie world..."
        });
    } catch (error) {
        res.status(500).json({
            error: "Encountered an error"
        });
    }
});

module.exports = router;