
// Auto-generated by AutoPilot on 25-07-2023 at 19:23:57

const express = require('express');
const router = express.Router();

//Generating 10 jokes on animals and returning a random one
router.get('/jokesv3', (req, res) => {
    let jokes = [
        'Q. Why did the chicken cross the playground? A. To get to the other slide.',
        'Q. What do you call a bear with no teeth? A. A gummy bear.',
        'Q. What did the fish say when it hit the wall? A. Dam.',
        'Q. Why don’t cats play poker in the jungle? A. Too many cheetahs.',
        'Q. What do you call a bee that can’t make up its mind? A. A maybe.',
        'Q. What did the elephant say to the naked man? A. How do you breathe through that tiny thing?',
        'Q. Why don’t lobsters share? A. They’re shellfish.',
        'Q. What do you get when you cross a bear and a skunk? A. Winnie the Phew.',
        'Q. What did the fish say when he hit the wall? A. Dam.',
        'Q. What did the porcupine say to the cactus? A. Is that you mommy?'
    ];

    //Generating a random index to return a random joke
    let randomIndex = Math.floor(Math.random() * jokes.length);
    let answer = jokes[randomIndex];

    //Returning a response with a random joke
    return res.status(200).json({
        'result': answer
    });
});

module.exports = router;