
// Auto-generated by AutoPilot on 24-07-2023 at 01:47:47

const express = require('express');
const router = express.Router();

// Generate a 10 happy near 2024 message and return a random one everytime.
const wishes = ['Happy new year 2024', 'Wish you a great year 2024', 'May 2024 be a fantastic year', 'Happy new year and all the best for 2024', 'Best wishes for the new year 2024', 'Wishing you a prosperous new year 2024', 'Bright and cheerful new year 2024', 'Wishing you a joyful new year 2024', 'Wishing you a new year of peace and joy 2024', 'Wishing you a year filled with happiness 2024']

// GET request for newYear route
router.get('/newYear', (req, res) => {
    try {
        // generate a random index from wishes array
        const randomIndex = Math.floor(Math.random() * wishes.length);
        // get the random wish
        const wish = wishes[randomIndex];
        // return the wish
        res.status(200).json({ result: wish });
    } catch (err) {
        // internal server error
        res.status(500).json({ error: 'Encountered an error' });
    }
});

module.exports = router;