
// Auto-generated by AutoPilot on 24-07-2023 at 00:59:48

const express = require('express');
const router = express.Router();
const {Translate} = require('@google-cloud/translate');

// Create a translation client
const translate = new Translate();

//Route to translate the text from english to hindi
router.post('/translate', async (req, res) => {
    // Get the text from query params
    const text = req.query.text;
    // Set the language to hindi
    const target = 'hi';
    try {
        // Translate the text
        const [translation] = await translate.translate(text, target);
        // Send the response
        res.status(200).json({ result: translation });
    } catch (err) {
        // If an error is encountered, send a 500 status code
        res.status(500).json({ error: 'Encountered an error' });
    }
});

module.exports = router;